### ISSUE TITLE
Worker Celery

### ISSUE THREAD

**Issue by leinlawun** [duckstax/RocketJoe#53]
- [ ] How tasks are set for workers for execution: eager and asynchronous. [Celery Task]
- [ ] Implement the mechanics of setting tasks for workers.

[Celery Task]: http://docs.celeryproject.org/en/latest/reference/celery.app.task.html

**Comment by leinlawun** [comment]
1. Task.apply ставит задачу локально.
2. Task.apply_async ставит задачу в Worker.
3. Task.apply_async позволяет изменить приоритет, отличающийся от дефолного.
4. Приоритет нельзя изменить.
5. В Task.apply_async можно задать kombu.Queue, kombu.Producer и kombu.Exchange.
   Предназначение всего, кроме первого, для меня не ясно. Впрочем, я не
   исключаю, что и первое я тоже не понимаю. kombu.Producer, судя по доке,
   позволяет идентифицировать клиента, отправившего задачу,
   kombu.Exchange - переопределить алгоритмы роутинга.
6. EagerResult.get, AsyncResult.get вызывать не рекомендуется, это может вызвать
   деадлоки.
7. Вместо этого рекомендуется делать связывание или, более "сахарный" вариант,
   chain, который похож на конвеер в bash.
8. Также есть другие операции конвеера, помимо операции chain: group, chord,
   map, startmap, chunks.

**Comment by kotbegemot** [comment]
```python3
import asyncio
from pyrocketjoe.celery import Celery

app = Celery()


@app.task()
def hello_world(a: int, b: int) -> None:
    print('Hello, World!')

    return a + b


@app.task()
async def async_hello_world(a: int, b: int) -> None:
    await asyncio.sleep(0)
    print('Async Hello, World!')
    return a + b

```
